# You can create generators as much as you want.
# Important: All generators should be named "generator1", "generator2", etc. 
# You can define the spawnrates of any block in the blocks-section.
# The spawnrates are in percent, for example 57.3 are 57,3%.
# All values together should be 100%. If all values together are higher or lower as 100, the plugin would'nt work correctly.
# The permissions are custom, so you can make a generator for VIPS, and give them the permission "oregen.vip".
# Are you finish with configuring? Just type /customoregen to reload the plugin!

# Note: If the Island's owner is offline, the cobblestone generator would be choose the first Generator-Config.

generators:
  generator1:
    # LVL 0
    blocks:
    # Please use Bukkit-Blocknames. List: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    - STONE:100
    permission: ''
    unlock_islandLevel: 0

  generator2:
    # LVL 10
    blocks:
    # Please use Bukkit-Blocknames. List: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    - STONE:95
    - SANDSTONE:5
    permission: ''
    unlock_islandLevel: 10

  generator3:
    # LVL 20
    blocks:
    # Please use Bukkit-Blocknames. List: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    - STONE:91
    - SANDSTONE:2
    - IRON_ORE:5
    - GOLD_ORE:2
    permission: ''
    unlock_islandLevel: 20

  generator4:
    # LVL 30
    blocks:
    # Please use Bukkit-Blocknames. List: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    - STONE:71
    - SANDSTONE:2
    - IRON_ORE:15
    - DIAMOND_ORE:1
    - EMERALD_ORE:1
    - GOLD_ORE:3
    - LAPIS_ORE:1
    - REDSTONE_ORE:2
    - COAL_ORE:4
    permission: ''
    unlock_islandLevel: 30

#Generator template
#  generatorX:
#    blocks:
#    - ORE:x.x
#    permission: ''
#    unlock_islandLevel: ''
 
# Here you can define worlds where the generator should not work
disabled-worlds:
- "wankercraft"
- "wankercraft_nether"
- "wankercraft_the_end"
- "Originalwank"
- "wankerdeuce"
- "guest_live"
- "Skynet"
